--CREATE DATABASE
CREATE DATABASE Project1
--CREATE TABLE
Create table PROJECT(
ID int primary key,
NAME varchar(30) not null,
MANAGER varchar(20),
RATING numeric (9,2))




-- INSERT ROW IN TABLE
INSERT INTO PROJECT VALUES(1, 'E-Commerce','Aakash',4.2);
INSERT INTO PROJECT VALUES(2, 'Bus Management','David',4);
INSERT INTO PROJECT VALUES(3, 'Food Delivery App','Pawan',4.5);
INSERT INTO PROJECT VALUES(4, 'Student Management','Srushti',3.5);
INSERT INTO PROJECT VALUES(5, 'Rent Website','Rihanna',2.9);
INSERT INTO PROJECT VALUES(6, 'Netfilx Clone','Riya',3);
INSERT INTO PROJECT VALUES(7, 'Hotel Website','Divya',4);
INSERT INTO PROJECT VALUES(8, 'Streaming Platform','Shivam',3);

-- SELECT ALL ROWS FROM TABLE
SELECT * FROM PROJECT;



-- SELECT PROJECTNAME FROM TABLE WHERE PROJECT RATING IS GREATER THAN 3
SELECT NAME FROM PROJECT WHERE RATING > 3;
�
-- ARRANGE ROWS IN ASCENDING ORDER OF RATING
SELECT * FROM PROJECT ORDER BY RATING ASC;



-- NEW TABLE ON MANAGERS
CREATE TABLE MANAGERS(
MANAGER_ID INT PRIMARY KEY,
MANAGERNAME VARCHAR(20),
SALARY INT);

INSERT INTO MANAGERS VALUES(1, 'Aakash',50000);
INSERT INTO MANAGERS VALUES(2, 'David', 70000);
INSERT INTO MANAGERS VALUES(3, 'Pawan', 75000);
INSERT INTO MANAGERS VALUES(4, 'Srushti', 55000);
INSERT INTO MANAGERS VALUES(5, 'Rihanna', 100000);
INSERT INTO MANAGERS VALUES(6, 'Riya', 75000);
INSERT INTO MANAGERS VALUES(7, 'Divya', 200000);

SELECT * FROM MANAGERS;

-- INNER JOIN
SELECT * FROM PROJECT INNER JOIN MANAGERS ON MANAGER = MANAGERNAME;

-- LEFT JOIN
SELECT * FROM PROJECT LEFT JOIN MANAGERS ON MANAGER = MANAGERNAME

-- RIGHT JOIN
SELECT * FROM PROJECT RIGHT JOIN MANAGERS ON MANAGER = MANAGERNAME

-- FULL JOIN
SELECT * FROM PROJECT FULL JOIN MANAGERS ON MANAGER = MANAGERNAME;